### ISSUE TITLE
llm2 core dump and container restart on each chat request, after printing CUDA devices

### ISSUE THREAD

**Issue by cantrust-hosting-cooperative** [nextcloud/llm2#50]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

First off, thank you for all the hard work on this app lately!   I have been following along the last week or two trying to get everything working as the latest bugs were worked out.  I was excited to finally get it downloading a model today and it registered the backend and it's really close for me, but I consistently get a crash when I try and use it, on two different ExApp hosts.  I am not sure what the issue is and am wondering if there's any way to get more debugging happening?  I might also try a local development install and see if I can get some more info that way... but in case this is a known/common issue:

### Steps to reproduce
1. Setup AppAPI  / ExApps in Nextcloud with nextcloud-dsp-proxy on GPU host.
2. Register a Deploy Daemon in setttings/admin/app_api , test the connection, and complete the test deploy.
3. Deploy llm2 and wait for it to become enabled and it to download the GGUF file.
4. Tail the llm2 logs on the ExApp container host with `docker logs -f nc_app_llm2`
5. Open the Nextcloud Assistant and switch to Chat Tab
6. Send a test chat message

### Expected behaviour
The LLM should be started and respond to the chat message

### Actual behaviour
The following log entries appear, but immediately after printing the CUDA devices, there is a core dump and the container restarts.
```
2025-02-20 23:14:21,820 - httpx - INFO - HTTP Request: GET https://company.example.com/ocs/v2.php/taskprocessing/tasks_provider/next?format=json "HTTP/1.1 200 OK"
2025-02-20 23:14:21,821 - main - INFO - chain: Meta-Llama-3.1-8B-Instruct-Q4_K_M:core:text2text:chat
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 2 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4060 Ti, compute capability 8.9, VMM: yes
  Device 1: NVIDIA GeForce RTX 4060 Ti, compute capability 8.9, VMM: yes
     [ crash happens here ]
```

I tried this on a second ExApp host too, with different video cards, and got the same results:

```
2025-02-20 20:26:37,806 - main - INFO - chain: Meta-Llama-3.1-8B-Instruct-Q4_K_M:core:text2text:chat
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 2 CUDA devices:
  Device 0: NVIDIA GeForce GTX 1070, compute capability 6.1, VMM: yes
  Device 1: NVIDIA GeForce GTX 1070, compute capability 6.1, VMM: yes
     [ crash happens here too ]
```
### Server configuration

both ExApp docker/GPU hosts are running:

- Debian 12 Bookworm
-  nvidia/cuda driver 570.86.15-1  (from nvidia apt repositories)
-  nvidia-container-toolkit 1.17.4-1 (from nvidia APT repositories)

nvidia-smi outputs:
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.86.15              Driver Version: 570.86.15      CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 Ti     On  |   00000000:02:00.0 Off |                  N/A |
|  0%   37C    P8             13W /  165W |     365MiB /  16380MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 4060 Ti     On  |   00000000:42:00.0 Off |                  N/A |
|  0%   38C    P8              8W /  165W |       5MiB /  16380MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            1678      C   /usr/local/bin/python                   222MiB |
|    0   N/A  N/A          512871      C   python3                                 128MiB |
+-----------------------------------------------------------------------------------------+

and on the second host:

+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.86.15              Driver Version: 570.86.15      CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1070        On  |   00000000:04:00.0 Off |                  N/A |
| 29%   27C    P8              7W /  151W |       3MiB /   8192MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce GTX 1070        On  |   00000000:42:00.0 Off |                  N/A |
| 32%   31C    P8              7W /  151W |       3MiB /   8192MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

**Web server:** Nginx

**Database:** Maria

**PHP version:** 8.2

**Nextcloud version:** 30.0.6

<details>
<summary>List of activated apps</summary>

```
Enabled:           
  - activity: 3.0.0                                               
  - admin_audit: 1.20.0
  - app_api: 4.0.6
  - appointments: 2.3.5                                           
  - assistant: 2.3.0                                              
  - bruteforcesettings: 3.0.0                                     
  - calendar: 5.1.0         
  - circles: 30.0.0                                               
  - cloud_federation_api: 1.13.0
  - collectives: 2.16.1                                           
  - comments: 1.20.1      
  - contacts: 7.0.0           
  - contactsinteraction: 1.11.0                                   
  - dashboard: 7.10.0                                             
  - dav: 1.31.1                                                   
  - deck: 1.14.3     
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0        
  - files: 2.2.0                                                  
  - files_downloadlimit: 3.0.0                                    
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0                                        
  - files_sharing: 1.22.0                                         
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0                                        
  - firstrunwizard: 3.0.0
  - forms: 4.3.7         
  - groupfolders: 18.1.0  
  - impersonate: 1.17.1
  - integration_google: 3.1.1
  - keeweb: 0.6.20  
  - logreader: 3.0.0  
  - lookup_server_connector: 1.18.0                          
  - mail: 4.2.0                                                   
  - maps: 1.5.0                                                   
  - nextcloud_announcements: 2.0.0                     
  - notes: 4.11.0                                                 
  - notifications: 3.0.0      
  - notify_push: 1.0.0        
  - oauth2: 1.18.1                                                
  - password_policy: 2.0.0
  - photos: 3.0.2                                                 
  - polls: 7.3.1                                                  
  - privacy: 2.0.0                                                
  - provisioning_api: 1.20.0
  - recommendations: 3.0.0
  - related_resources: 1.5.0                                      
  - richdocuments: 8.5.3                                          
  - serverinfo: 2.0.0                                             
  - settings: 1.13.0                                              
  - sharebymail: 1.20.0                                           
  - snappymail: 2.38.2                                                                                                               
  - spreed: 20.1.4                                                
  - support: 2.0.0   
  - survey_client: 2.0.0
  - systemtags: 1.20.0 
  - tables: 0.8.4    
  - tasks: 0.16.1             
  - text: 4.1.0   
  - theming: 2.6.0          
  - twofactor_backupcodes: 1.19.0 
  - twofactor_email: 2.7.4                                                                                                           
  - twofactor_nextcloud_notification: 4.0.0                                                                                          
  - twofactor_totp: 12.0.0-dev                                    
  - updatenotification: 1.20.0                                    
  - user_status: 1.10.0                                           
  - viewer: 3.0.0                                                 
  - weather_status: 1.10.0
  - webhook_listeners: 1.1.0-dev
  - whiteboard: 1.0.5
  - workflowengine: 2.12.0             
```
</details>

<details>
<summary>Nextcloud configuration</summary>
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "company.example.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "30.0.6.2",
        "overwrite.cli.url": "https:\/\/company.example.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "timeout": 1.5
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_smtpdebug": "false",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpsecure": "",
        "mail_smtpstreamoptions": {
            "ssl": {
                "allow_self_signed": true,
                "verify_peer": false,
                "verify_peer_name": false
            }
        },
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "simpleSignUpLink.shown": false,
        "defaultapp": "apporder",
        "default_phone_region": "CA",
        "skeletondirectory": "\/home\/nextcloud\/sites\/company.example.com\/skeletondirectory",
        "app_install_overwrite": [
            "spreed",
            "jitsi",
            "apporder",
            "keeweb",
            "twofactor_email",
            "llm",
            "files_frommail"
        ],
        "memories.exiftool": "\/home\/nextcloud\/sites\/company.example.com\/web\/apps\/memories\/bin-ext\/exiftool-amd64-glibc",
        "memories.vod.path": "\/home\/nextcloud\/sites\/company.example.com\/web\/apps\/memories\/bin-ext\/go-vod-amd64",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "trashbin_retention_obligation": "auto,90",
        "memories.db.triggers.fcu": true
    }
}

```
</details>
